### ISSUE TITLE
techotom-speed-control div gets added to hidden ytd-miniplayer div

### ISSUE THREAD

**Issue by chigozienri** [tomsaleeba/custom-youtube-playback-speed#2]
YouTube has changed to add a hidden `<div id="player-container" class="style-scope ytd-miniplayer">`, which the `techotom-speed-control` div now gets added to, instead of the main video (which is now in a div with no id, but class `html5-video-player`).

**Comment by tomsaleeba** [comment]
Thanks for the report and digging into what the fix should be @chigozienri. See if my latest commit works for you.
